#!/usr/bin/env python3
"""Generate an index of icon assets available for UI work.

Scans every known icon location in the repo, not just the primary external-icons
pack directory. See Documents/architecture/2026-07_asset-file-structure-taxonomy.md
for why icons currently live in more than one place and the plan to consolidate them
under Assets/Art/Icons/ over time — this script indexes the current reality so the
index stays useful in the meantime.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_JSON = REPO_ROOT / "Documents" / "icon-index.json"
OUTPUT_MD = REPO_ROOT / "Documents" / "icon-index.md"
LICENSE_FILE = REPO_ROOT / "Assets" / "Art" / "Icons" / "external icons" / "license.txt"

ICON_EXTENSIONS = {"svg", "png"}

# (source label, root dir relative to REPO_ROOT). Ordered roughly by size.
# Non-"external" sources are audited scatter, not the intended long-term home —
# see the taxonomy doc's Phase 1 for the planned consolidation into Assets/Art/Icons/.
ICON_ROOTS: list[tuple[str, str]] = [
    ("external", "Assets/Art/Icons/external icons"),
    ("map-editor", "Assets/Art/Icons/map-editor"),
    ("heroicons", "Assets/Art/Graphics/UI/Misc/Heroicons"),
    ("interaction-icons", "Assets/Art/Graphics/UI/Interactions/InteractionIcons"),
    ("inventory-icons", "Assets/Art/Graphics/UI/Containers/InventoryIcons"),
    ("rendered-icons", "Assets/Art/Graphics/Misc/RenderedIcons"),
    ("alert-stack", "Assets/Content/Systems/UI/MainHud/Icons/AlertStack"),
]


@dataclass
class IconRecord:
    name: str
    stem: str
    extension: str
    source: str
    pack: str
    path: str
    tags: list[str]

    def to_dict(self) -> dict:
        return asdict(self)


def slug_tags(stem: str) -> list[str]:
    return [part for part in stem.lower().split("-") if part]


def walk_icon_roots() -> list[IconRecord]:
    records: list[IconRecord] = []

    for source, rel_root in ICON_ROOTS:
        root = REPO_ROOT / rel_root
        if not root.is_dir():
            continue

        for file_path in sorted(root.rglob("*")):
            if not file_path.is_file() or file_path.name.endswith(".meta"):
                continue
            if file_path.suffix.lstrip(".").lower() not in ICON_EXTENSIONS:
                continue

            pack = file_path.parent.name
            stem = file_path.stem
            relative = file_path.relative_to(REPO_ROOT)

            records.append(
                IconRecord(
                    name=file_path.name,
                    stem=stem,
                    extension=file_path.suffix.lstrip(".").lower(),
                    source=source,
                    pack=pack,
                    path=relative.as_posix(),
                    tags=slug_tags(stem),
                )
            )

    return records


def build_pack_stats(records: list[IconRecord]) -> list[dict]:
    counts = Counter(record.pack for record in records if record.source == "external")
    return [
        {"pack": pack, "count": count}
        for pack, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))
    ]


def build_source_stats(records: list[IconRecord]) -> list[dict]:
    counts = Counter(record.source for record in records)
    return [
        {"source": source, "count": counts.get(source, 0), "root": root}
        for source, root in ICON_ROOTS
    ]


def render_markdown(payload: dict) -> str:
    summary = payload["summary"]
    packs = payload["packs"][:15]
    sources = payload["sources"]

    lines = [
        "# Icon index (agent reference)",
        "",
        "> Generated by `Tools/generate_icon_index.py`. Re-run after adding icons.",
        "",
        "Catalog of icon assets across the repo. The majority are",
        "[game-icons.net](https://game-icons.net) SVGs under `Assets/Art/Icons/external icons/`,",
        "but several other icon sets currently live elsewhere (audited in",
        "[2026-07_asset-file-structure-taxonomy.md](architecture/2026-07_asset-file-structure-taxonomy.md));",
        "this index covers all of them so it stays accurate ahead of that consolidation.",
        "",
        f"**Generated:** {payload['generated_at']}",
        "",
        "## When to use",
        "",
        "Consult this index **before** sourcing or creating new icons when:",
        "",
        "- A UI screen needs a button, status, or category glyph",
        "- You want an icon for a tool, machine, body part, or game concept",
        "- You need to check whether a suitable icon already exists in the project",
        "",
        "**All new icon assets belong under `Assets/Art/Icons/<Source>/`** — never add a new icon",
        "folder under `Graphics/` or `Content/Systems/*`; see the taxonomy doc linked above.",
        "",
        "## Agent workflow",
        "",
        "1. Search [`icon-index.json`](icon-index.json) by `stem`, `tags`, `pack`, or `source`.",
        "2. Use the `path` field as the repo-relative asset path.",
        "3. Prefer descriptive tag matches (e.g. `welder`, `power`, `medical`).",
        "4. Regenerate after adding icons: `python3 Tools/generate_icon_index.py`.",
        "",
        "### Search examples",
        "",
        "```bash",
        "# Find icons related to power/electricity",
        'jq \'.icons[] | select(.tags[]? | test(\"power|bolt|electric\"))\' Documents/icon-index.json',
        "",
        "# Find a specific icon by filename stem",
        'jq \'.icons[] | select(.stem == \"microscope\")\' Documents/icon-index.json',
        "",
        "# List icons in a contributor pack",
        'jq \'.icons[] | select(.pack == \"delapouite\")\' Documents/icon-index.json',
        "",
        "# List icons from a non-external-icons source (e.g. the alert-stack HUD set)",
        'jq \'.icons[] | select(.source == \"alert-stack\")\' Documents/icon-index.json',
        "",
        "# Quick grep by keyword",
        'grep -i "wrench" Documents/icon-index.json',
        "```",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|------:|",
        f"| Total icons | {summary['total_icons']} |",
        f"| Sources | {summary['source_count']} |",
        f"| Contributor packs (`external` source) | {summary['pack_count']} |",
        f"| SVG icons | {summary['svg_count']} |",
        "",
        "## By source",
        "",
        "| Source | Count | Root |",
        "|--------|------:|------|",
    ]

    for src in sources:
        lines.append(f"| {src['source']} | {src['count']} | `{src['root']}` |")

    lines.extend(
        [
            "",
            "Every source except `external` and `map-editor` is audited scatter, not the intended",
            "home — see the taxonomy doc's Phase 1 for the planned move into `Assets/Art/Icons/`.",
            "",
            "## Top contributor packs (`external` source)",
            "",
            "| Pack | Icons |",
            "|------|------:|",
        ]
    )

    for pack in packs:
        lines.append(f"| {pack['pack']} | {pack['count']} |")

    if len(payload["packs"]) > 15:
        lines.append(f"| … | {len(payload['packs']) - 15} more packs in JSON |")

    lines.extend(
        [
            "",
            "Icons in the `external` source are grouped by original game-icons.net contributor",
            "(e.g. `delapouite`, `lorc`, `caro-asercion`). Filename stems use kebab-case and map to",
            "searchable tags.",
            "",
            "Full data: [`icon-index.json`](icon-index.json)",
            "",
            "## License",
            "",
            "`external` source icons are from [game-icons.net](https://game-icons.net) under CC BY 3.0",
            "(some CC0). See `Assets/Art/Icons/external icons/license.txt` for contributor attribution.",
            "Include \"Icons made by {author}\" in derivative work per the license. Other sources carry",
            "whatever license applied when they were added — check before reusing outside this project.",
            "",
            "## Regenerating",
            "",
            "```bash",
            "python3 Tools/generate_icon_index.py",
            "```",
            "",
            "## Related",
            "",
            "- [art-asset-index.md](art-asset-index.md) — models, textures, sounds",
            "- [architecture/2026-07_asset-file-structure-taxonomy.md](architecture/2026-07_asset-file-structure-taxonomy.md) — icon-scatter audit + consolidation plan",
            "- [AGENTS.md](../AGENTS.md) — agent navigation",
            "",
        ]
    )

    return "\n".join(lines)


def build_payload(records: list[IconRecord]) -> dict:
    packs = build_pack_stats(records)
    sources = build_source_stats(records)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "purpose": (
            "Agent reference for locating icon assets across the repo, including sets outside "
            "Assets/Art/Icons/ pending consolidation (see the asset-file-structure-taxonomy doc)."
        ),
        "sources": sources,
        "summary": {
            "total_icons": len(records),
            "source_count": len(sources),
            "pack_count": len(packs),
            "svg_count": sum(1 for item in records if item.extension == "svg"),
        },
        "packs": packs,
        "icons": [record.to_dict() for record in records],
    }


def main() -> None:
    records = walk_icon_roots()
    payload = build_payload(records)

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_JSON.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")

    with OUTPUT_MD.open("w", encoding="utf-8") as handle:
        handle.write(render_markdown(payload))

    summary = payload["summary"]
    print(
        f"Wrote {OUTPUT_JSON} ({summary['total_icons']} icons, "
        f"{summary['source_count']} sources, {summary['pack_count']} external packs)"
    )
    print(f"Wrote {OUTPUT_MD}")


if __name__ == "__main__":
    main()
